package com.pc1.backendrupay.enums;

public enum TypeTicket {

    LUNCH,
    STUDENT_LUNCH_TICKET,
    STUDENT_DINNER_TICKET,
    EXTERNAL_DINNER_TICKET,
    EXTERNAL_LUNCH_TICKET,
    SCHOLARSHIP_LUNCH_TICKET,
    SCHOLARSHIP_DINNER_TICKET,
    DINNER
}
